CREATE DATABASE SIRKET
USE SIRKET

CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
SAA NVARCHAR(100),
VEZIFEID INT REFERENCES VEZIFE(ID),
SALARY MONEY)

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100))

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100))

CREATE TABLE PRODUCT(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(100),
ALISQIYMETI MONEY,
SATISQIYMETI MONEY)

CREATE TABLE SALE(
ID INT PRIMARY KEY IDENTITY,
PRODUCTID INT REFERENCES PRODUCT(ID),
ISCIID INT REFERENCES ISCI(ID),
FILIALID INT REFERENCES FILIAL(ID),
SATISTARIXI DATE)

--SORGU1:
--Satış cədvəlində işçilərin,satılan məhsulların,satışın olduğu filialın,məhsulun alış və satış qiyməti yazılsın.
SELECT SAA, PRODUCT.NAME AS 'PRODUCT NAME', FILIAL.NAME AS 'FILIAL NAME', 
PRODUCT.ALISQIYMETI AS 'ALIS QIYMETI', PRODUCT.SATISQIYMETI AS 'SATIS QIYMETI' FROM SALE
JOIN ISCI 
ON ISCIID=ISCI.ID
JOIN PRODUCT
ON PRODUCTID=PRODUCT.ID
JOIN FILIAL
ON FILIAL.ID=FILIALID

--SORGU2
--Bütün satışların cəmini tap.
SELECT SUM(PRODUCT.SATISQIYMETI) FROM SALE JOIN PRODUCT
ON PRODUCT.ID=PRODUCTID

--SORGU3
--Cari ayda məhsul satışından gələn yekun məbləği tap
SELECT SUM(PRODUCT.SATISQIYMETI)
FROM SALE JOIN PRODUCT
ON PRODUCT.ID=PRODUCTID
WHERE MONTH(SALE.SATISTARIXI)=MONTH(GETDATE())

--SORGU4
--Hər işçinin satdığı məhsul sayını tap
SELECT SAA AS 'ISCI', COUNT(PRODUCTID) AS 'MEHSUL SAYI' FROM SALE 
JOIN PRODUCT ON PRODUCT.ID=PRODUCTID
JOIN ISCI ON ISCI.ID=ISCIID
GROUP BY ISCI.SAA

--SORGU5
--Bu gün üzrə ən çox məhsul satılan filialı tap.
SELECT TOP 1 FILIAL.NAME 'FILIAL', COUNT(PRODUCTID)'PRODUCTSAYI' FROM SALE JOIN FILIAL ON FILIAL.ID=SALE.FILIALID
WHERE DAY(SALE.SATISTARIXI)=DAY(GETDATE()) GROUP BY FILIAL.NAME

--SORGU6
--Cari ayda ən çox satılan məhsulu tap.
SELECT TOP 1 COUNT(PRODUCT.ID) 'SAY' , PRODUCT.NAME 'NAME' FROM PRODUCT JOIN SALE ON PRODUCT.ID=PRODUCTID 
WHERE MONTH(SATISTARIXI)=MONTH(GETDATE()) GROUP BY PRODUCT.NAME
